#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "GHACConnectManager.h"
#import "GHACConnectModel.h"
#import "GHACConnectSDK.h"
#import "HCAlertController.h"
#import "HCCodeInputView.h"
#import "HCCommonEnum.h"
#import "HCCommonMacros.h"
#import "HCCountDownButton.h"
#import "HCDBHelper.h"
#import "HCDBManager.h"
#import "HCDismissAnimator.h"
#import "HCImagePicker.h"
#import "HCLayoutButton.h"
#import "HCPresentAnimator.h"
#import "HCThirdMacros.h"
#import "HCBindVehicleSuccessViewController.h"
#import "HCScanAuthSucceedViewController.h"
#import "HCScanLoginSucceedViewController.h"
#import "HCScanQRViewController.h"
#import "HCAddressDetailViewController.h"
#import "HCNearbyViewController.h"
#import "HCSearchResultViewController.h"
#import "HCTravelSearchViewController.h"
#import "HCTravelViewController.h"
#import "HCAddressInfoView.h"
#import "HCAnimateSearchBarView.h"
#import "HCAnnotationInfoView.h"
#import "HCEmptyHistoryDataView.h"
#import "HCEmptyNetErrorView.h"
#import "HCEmptySearchDataView.h"
#import "HCNearbyCollectHeaderView.h"
#import "HCNearbyCollectionViewCell.h"
#import "HCOnMapItem.h"
#import "HCResultSearchBar.h"
#import "HCSearchBar.h"
#import "HCSearchFuzzyTableViewCell.h"
#import "HCSearchResultHistoryTableViewCell.h"
#import "HCSearchResultTableView.h"
#import "HCSendToCarView.h"
#import "HCSetDestinationView.h"
#import "HCSetFenceCenterView.h"
#import "HCTravelSearchButton.h"
#import "HCTravelSearchTableView.h"
#import "HCUserAnnotationCalloutView.h"
#import "HCUserAnnotationView.h"
#import "HCVehicleAnnotationView.h"
#import "HCCarTeamInfoModel.h"
#import "HCFenceModel.h"
#import "HCNearbyClassifyContentModel.h"
#import "HCNearbyClassifyModel.h"
#import "HCQMapCommonSearchResModel.h"
#import "HCSocketReceiveModel.h"
#import "HCQMapService.h"
#import "HCMapAppSheet.h"
#import "HCOpenURLUtils.h"
#import "HCQMapUtils.h"
#import "HCVehicleTeamUtils.h"
#import "HCAirActionSheet.h"
#import "HCCallbackViewModel.h"
#import "HCConditionStateView.h"
#import "HCConditionVehicleView.h"
#import "HCControlState.h"
#import "HCEditVehicleNicknameViewController.h"
#import "HCGradientCountLabel.h"
#import "HCHomeAirConditionerTableViewCell.h"
#import "HCHomeConditionTableViewCell.h"
#import "HCHomeEmptyViewController.h"
#import "HCHomeFunctionConfigModel.h"
#import "HCHomeNavigationRecordTableViewCell.h"
#import "HCHomeTravelTableViewCell.h"
#import "HCHomeVehicleInfoTableViewCell.h"
#import "HCHomeVehicleViewController.h"
#import "HCHomeView.h"
#import "HCHomeViewController.h"
#import "HCMessageSettingTableCell.h"
#import "HCRelieveVehicleViewController.h"
#import "HCRemoteControlLoadingView.h"
#import "HCRemoteControlTableViewCell.h"
#import "HCRemoteKeyMacros.h"
#import "HCSettingTableViewCell.h"
#import "HCSettingViewController.h"
#import "HCTransitionAnimation.h"
#import "HCVehicleConditionViewController.h"
#import "HCVehicleEnergyView.h"
#import "HCVehicleGPSInfoModel.h"
#import "HCVehicleManagerTableViewCell.h"
#import "HCVehicleManagerViewController.h"
#import "HCVehicleNicknameTableCell.h"
#import "HCVehicleSettingConfigModel.h"
#import "HCVehicleSettingModel.h"
#import "HCVehicleSettingViewController.h"
#import "HCVehicleStateModel.h"

FOUNDATION_EXPORT double GHACConnectSDKVersionNumber;
FOUNDATION_EXPORT const unsigned char GHACConnectSDKVersionString[];

